title: Jayesh Parihar
logo: /[Photo](https://github.com/user-attachments/assets/bbade0b5-ccca-4a86-9e35-77e7e9aa85aa)/headshot_circle.png
#Description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
